package br.com.btg360.constants

object Message {

  val START_LOG: String = "START LOG ================================================================================"
  val END_LOG: String = "END LOG =================================================================================="
  val CHANNEL_RUNNING = "***** CHANNEL RUNNING: %s *****"
  val ITEMS_NOT_FOUND = "ITEMS NOT FOUND"
  val TOTAL_ITEMS_FOUND = "TOTAL ITEMS FOUND: %d"
  val TOTAL_DAILY_LIMIT_REMOVED = "QUANTITY OF ITEMS WITH DAILY SHIPPING LIMIT REMOVED: %d"
  val TOTAL_OPTOUT_REMOVED = "QUANTITY OF ITEMS WITH OPTOUT REMOVED: %d"
  val PRODUCT_TABLE_NAME = "PRODUCT TABLE NAME: %s"
  val CONSOLIDATED_TABLE_NAME = "CONSOLIDATED TABLE NAME: %s"
  val CONSOLIDATED_TABLE_NOT_FOUND = "CONSOLIDATED TABLE %s NOT FOUND"
  val TRANSACTIONAL_SUCCESS = "DATA SAVED IN TRANSACTIONAL SUCCESSFULLY"
  val TRANSACTIONAL_ERROR = "ERROR WHILE TRYING TO SAVE DATA IN TRANSACTIONAL"

}
